#include "main.h"

Controller master (E_CONTROLLER_MASTER);

Motor leftBase1 (LEFTBASE1, E_MOTOR_GEARSET_18, 0, E_MOTOR_ENCODER_DEGREES);
Motor leftBase2 (LEFTBASE2, E_MOTOR_GEARSET_18, 1, E_MOTOR_ENCODER_DEGREES);
Motor rightBase1 (RIGHTBASE1, E_MOTOR_GEARSET_18, 1, E_MOTOR_ENCODER_DEGREES);
Motor rightBase2 (RIGHTBASE2, E_MOTOR_GEARSET_18, 0, E_MOTOR_ENCODER_DEGREES);
Motor leftLift (LEFTLIFT, E_MOTOR_GEARSET_18, 0, E_MOTOR_ENCODER_DEGREES);
Motor rightLift (RIGHTLIFT, E_MOTOR_GEARSET_18, 1, E_MOTOR_ENCODER_DEGREES);
Motor intake1 (INTAKE1, E_MOTOR_GEARSET_18, 0, E_MOTOR_ENCODER_DEGREES);
Motor intake2 (INTAKE2, E_MOTOR_GEARSET_18, 0, E_MOTOR_ENCODER_DEGREES);