#include "main.h"

Controller master (E_CONTROLLER_MASTER);

Motor leftBase1 (4, E_MOTOR_GEARSET_18, 0, E_MOTOR_ENCODER_DEGREES);
Motor leftBase2 (5, E_MOTOR_GEARSET_18, 0, E_MOTOR_ENCODER_DEGREES);
Motor rightBase1 (6, E_MOTOR_GEARSET_18, 1, E_MOTOR_ENCODER_DEGREES);
Motor rightBase2 (7, E_MOTOR_GEARSET_18, 1, E_MOTOR_ENCODER_DEGREES);
Motor intake1 (3, E_MOTOR_GEARSET_18, 0, E_MOTOR_ENCODER_DEGREES);
Motor intake2 (2, E_MOTOR_GEARSET_18, 1, E_MOTOR_ENCODER_DEGREES);
Motor tray (1, E_MOTOR_GEARSET_18, 0, E_MOTOR_ENCODER_DEGREES);